on: pull_request
name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@master
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      with:
        args: WordPress,WordPress-Core,WordPress-Docs
